import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Link, useLocation } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { LogOut, LayoutDashboard, Home, Sparkles } from 'lucide-react';
export const Layout = ({ children }) => {
    const { user, logout } = useAuth();
    const location = useLocation();
    const isActive = (path) => location.pathname === path;
    return (_jsxs("div", { className: "min-h-screen bg-gray-50", children: [_jsx("nav", { className: "bg-white shadow-sm border-b border-gray-200", children: _jsx("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: _jsxs("div", { className: "flex justify-between items-center h-16", children: [_jsxs("div", { className: "flex items-center space-x-8", children: [_jsxs(Link, { to: "/", className: "flex items-center space-x-2", children: [_jsx(LayoutDashboard, { className: "h-8 w-8 text-indigo-600" }), _jsx("span", { className: "text-xl font-bold text-gray-900", children: "Project Pulse" })] }), _jsxs("div", { className: "hidden md:flex space-x-4", children: [_jsxs(Link, { to: "/", className: `flex items-center space-x-1 px-3 py-2 rounded-md text-sm font-medium transition-colors ${isActive('/')
                                                    ? 'text-indigo-600 bg-indigo-50'
                                                    : 'text-gray-700 hover:text-indigo-600 hover:bg-gray-50'}`, children: [_jsx(Home, { className: "h-4 w-4" }), _jsx("span", { children: "Home" })] }), _jsxs(Link, { to: "/features", className: `flex items-center space-x-1 px-3 py-2 rounded-md text-sm font-medium transition-colors ${isActive('/features')
                                                    ? 'text-indigo-600 bg-indigo-50'
                                                    : 'text-gray-700 hover:text-indigo-600 hover:bg-gray-50'}`, children: [_jsx(Sparkles, { className: "h-4 w-4" }), _jsx("span", { children: "Features" })] }), user && (_jsxs(Link, { to: "/dashboard", className: `flex items-center space-x-1 px-3 py-2 rounded-md text-sm font-medium transition-colors ${isActive('/dashboard')
                                                    ? 'text-indigo-600 bg-indigo-50'
                                                    : 'text-gray-700 hover:text-indigo-600 hover:bg-gray-50'}`, children: [_jsx(LayoutDashboard, { className: "h-4 w-4" }), _jsx("span", { children: "Dashboard" })] }))] })] }), _jsx("div", { className: "flex items-center space-x-4", children: user ? (_jsxs(_Fragment, { children: [_jsxs("span", { className: "text-sm text-gray-700", children: ["Hello, ", _jsx("span", { className: "font-semibold", children: user.email })] }), _jsxs("button", { onClick: logout, className: "flex items-center space-x-1 px-4 py-2 text-sm font-medium text-white bg-indigo-600 rounded-lg hover:bg-indigo-700 transition-colors", children: [_jsx(LogOut, { className: "h-4 w-4" }), _jsx("span", { children: "Logout" })] })] })) : (_jsxs(_Fragment, { children: [_jsx(Link, { to: "/login", className: "px-4 py-2 text-sm font-medium text-gray-700 hover:text-indigo-600 transition-colors", children: "Login" }), _jsx(Link, { to: "/register", className: "px-4 py-2 text-sm font-medium text-white bg-indigo-600 rounded-lg hover:bg-indigo-700 transition-colors", children: "Sign Up" })] })) })] }) }) }), _jsx("main", { children: children }), _jsx("footer", { className: "bg-white border-t border-gray-200 mt-auto", children: _jsx("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6", children: _jsx("p", { className: "text-center text-sm text-gray-500", children: "\u00A9 2025 Project Pulse by Nexventures Ltd. All rights reserved." }) }) })] }));
};
